/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.software.views;

import com.software.controller.ClientController;

import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author monicag
 */
public class Connection extends javax.swing.JFrame {

    private Socket socketConnection;
    private ClientController clientController;

    /**
     * Creates new form Connection
     */
    public Connection() {
        socketConnection = new Socket();
        clientController = new ClientController();
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ParenPanel = new javax.swing.JPanel();
        ConnectLabel = new javax.swing.JLabel();
        IpTextField = new javax.swing.JTextField();
        PortTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Connection");
        setLocationByPlatform(true);

        ParenPanel.setBackground(new java.awt.Color(84, 188, 246));

        ConnectLabel.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        ConnectLabel.setForeground(new java.awt.Color(255, 255, 255));
        ConnectLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ConnectLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\camm0\\Documents\\NetBeansProjects\\FtpClient\\Icons\\connect.png")); // NOI18N
        ConnectLabel.setText("Conectar");
        ConnectLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConnectLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConnectLabelMouseClicked(evt);
            }
        });

        IpTextField.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        IpTextField.setBorder(null);
        IpTextField.setSelectionColor(new java.awt.Color(255, 255, 255));

        PortTextField.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        PortTextField.setBorder(null);
        PortTextField.setSelectionColor(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dirección IP");

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Puerto");

        javax.swing.GroupLayout ParenPanelLayout = new javax.swing.GroupLayout(ParenPanel);
        ParenPanel.setLayout(ParenPanelLayout);
        ParenPanelLayout.setHorizontalGroup(
            ParenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParenPanelLayout.createSequentialGroup()
                .addGroup(ParenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ParenPanelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(ParenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(IpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(ParenPanelLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(ConnectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        ParenPanelLayout.setVerticalGroup(
            ParenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParenPanelLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(IpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(PortTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConnectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ParenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ParenPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConnectLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConnectLabelMouseClicked
        String ipAddress = IpTextField.getText();
        String port = PortTextField.getText();
        System.out.println(ipAddress);
        System.out.println(port);
        // solicitar conexion
        Socket requestConnection = clientController.connectToServer(port, ipAddress);
        // verificar conexion
        if (requestConnection == null) {
            // Acciones si la conexión no se pudo establecer
            InputDialogUtils.showConnectionErrorDialog();
            // Limpiar cambios de texto
            IpTextField.setText("");
            PortTextField.setText("");
        } else {
            // mensaje si la conexión se estableció correctamente
            InputDialogUtils.showConnectionSuccessDialog();
            // Limpiar cambios de texto
            IpTextField.setText("");
            PortTextField.setText("");
            try {
                Thread.sleep(1500);
            } catch (InterruptedException ex) {
                Logger.getLogger(Connection.class.getName()).log(Level.SEVERE, null, ex);
            }
            // Ocultar la ventana padre del componente actual (ventana Connection)
            setVisible(false);
            // Crear el panel FTP y pasar el socket
            FtpPanel ftpPanel = new FtpPanel(requestConnection, clientController);
            // Mostrar la ventana FtpPanel
            ftpPanel.setVisible(true);
            // Cerrar la ventana Connection
            dispose();
        }
    }//GEN-LAST:event_ConnectLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Connection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Connection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Connection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Connection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Connection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConnectLabel;
    private javax.swing.JTextField IpTextField;
    private javax.swing.JPanel ParenPanel;
    private javax.swing.JTextField PortTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
