/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.software.views;

import com.software.entities.User;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author camm0
 */
public class UsersConnected extends javax.swing.JFrame {

    /**
     * Creates new form UsersConnected
     */
    public UsersConnected() {
        initComponents();
    }
    
    public UsersConnected(List<User> userList) {
        initComponents();
        
        DefaultTableModel model = (DefaultTableModel) UsersTable.getModel();
        
        for (User user : userList) {
            String[] row = {user.getIp(), user.getDate(), user.getHour()};
            model.addRow(row);
        }
        
        UsersTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JParentPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UsersTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JParentPanel.setBackground(new java.awt.Color(255, 255, 255));

        UsersTable.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        UsersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dirección IP", "Fecha", "Hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        UsersTable.setEnabled(false);
        UsersTable.setFocusable(false);
        UsersTable.setGridColor(new java.awt.Color(255, 255, 255));
        UsersTable.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(UsersTable);

        javax.swing.GroupLayout JParentPanelLayout = new javax.swing.GroupLayout(JParentPanel);
        JParentPanel.setLayout(JParentPanelLayout);
        JParentPanelLayout.setHorizontalGroup(
            JParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
        JParentPanelLayout.setVerticalGroup(
            JParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JParentPanel;
    private javax.swing.JTable UsersTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
